title = "Long Straddle"

[[contracts]]
type = "Call"
position = "BUY"
price = 5
expiration = "2023-01-01"
strike = 40

[[contracts]]
type = "Put"
position = "BUY"
price = 5
expiration = "2023-01-01"
strike = 40
