title = "Short Strangle"

[[contracts]]
type = "Call"
position = "SELL"
price = 5
expiration = "2023-01-01"
strike = 60 

[[contracts]]
type = "Put"
position = "SELL"
price = 5
expiration = "2023-01-01"
strike = 40
