title = "Short Butterfly"

[[contracts]]
type = "Call"
position = "SELL"
price = 5
expiration = "2023-01-01"
strike = 40

[[contracts]]
type = "Call"
position = "BUY"
price = 5
expiration = "2023-01-01"
strike = 50 

[[contracts]]
type = "Call"
position = "BUY"
price = 5
expiration = "2023-01-01"
strike = 50 

[[contracts]]
type = "Call"
position = "SELL"
price = 5
expiration = "2023-01-01"
strike = 60 
